"""add user auth and org tables

Revision ID: 7b167543c137
Revises: 
Create Date: 2026-05-15 20:56:57.356346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b167543c137'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('otp_hash', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Enum('signup', 'reset_password', name='otp_purpose', schema='insightpilot'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='insightpilot'
    )
    op.create_index(op.f('ix_insightpilot_email_otps_email'), 'email_otps', ['email'], unique=False, schema='insightpilot')
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='insightpilot'
    )
    op.create_index(op.f('ix_insightpilot_organizations_slug'), 'organizations', ['slug'], unique=True, schema='insightpilot')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='insightpilot'
    )
    op.create_index(op.f('ix_insightpilot_users_email'), 'users', ['email'], unique=True, schema='insightpilot')
    op.create_table('org_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='org_role', schema='insightpilot'), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['insightpilot.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['insightpilot.organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['insightpilot.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='insightpilot'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_members', schema='insightpilot')
    op.drop_index(op.f('ix_insightpilot_users_email'), table_name='users', schema='insightpilot')
    op.drop_table('users', schema='insightpilot')
    op.drop_index(op.f('ix_insightpilot_organizations_slug'), table_name='organizations', schema='insightpilot')
    op.drop_table('organizations', schema='insightpilot')
    op.drop_index(op.f('ix_insightpilot_email_otps_email'), table_name='email_otps', schema='insightpilot')
    op.drop_table('email_otps', schema='insightpilot')
    # ### end Alembic commands ###
