"""add_token_version_to_users

Revision ID: d5b4549f7c88
Revises: fa57497ead90
Create Date: 2026-05-16 00:55:12.912569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b4549f7c88'
down_revision: Union[str, None] = 'fa57497ead90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False), schema='insightpilot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version', schema='insightpilot')
    # ### end Alembic commands ###
