"""add_data_sources_table

Revision ID: fa57497ead90
Revises: 7b167543c137
Create Date: 2026-05-16 00:21:56.983056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa57497ead90'
down_revision: Union[str, None] = '7b167543c137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ds_type', sa.Enum('postgresql', 'mysql', 'mssql', name='ds_type', schema='insightpilot'), nullable=False),
    sa.Column('host', sa.String(length=512), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['insightpilot.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['insightpilot.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='insightpilot'
    )
    op.create_index(op.f('ix_insightpilot_data_sources_org_id'), 'data_sources', ['org_id'], unique=False, schema='insightpilot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insightpilot_data_sources_org_id'), table_name='data_sources', schema='insightpilot')
    op.drop_table('data_sources', schema='insightpilot')
    # ### end Alembic commands ###
